# Generated by Django 6.0.3 on 2026-04-07 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='nombre',
            new_name='nombre_paciente',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='parentesco',
            field=models.CharField(default=0, help_text='Ej: Padre, Madre, Tío', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnostico',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='familiares', to='core.cliente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato de Servicio'), ('COTIZACION', 'Cotización'), ('CUENTA_COBRO', 'Cuenta de Cobro')], max_length=20)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
    ]
