# Generated by Django 6.0.3 on 2026-04-07 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_rename_nombre_paciente_nombre_paciente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cedula',
            new_name='numero_identificacion',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='diagnostico',
            new_name='direccion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='monto_total',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cantidad_duracion',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], default='CC', max_length=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_servicio',
            field=models.CharField(choices=[('8H', 'Prestación de servicios auxiliar de enfermería (8 Horas)'), ('12H', 'Prestación de servicios auxiliar de enfermería (12 Horas)'), ('24H', 'Prestación de servicios auxiliar de enfermería (24 Horas)')], default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='unidad_duracion',
            field=models.CharField(choices=[('DIAS', 'Días'), ('SEM', 'Semanas'), ('MES', 'Meses'), ('IND', 'Indefinido')], default='MES', max_length=5),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_diario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_mensual',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='valor_semanal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='condicion',
            field=models.TextField(default=0, verbose_name='Condición Médica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_identificacion',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('NIT', 'NIT'), ('PAS', 'Pasaporte')], default='CC', max_length=5),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='parentesco',
            field=models.CharField(max_length=100, verbose_name='Relación con el Cliente'),
        ),
    ]
